version: '3'
services:
  db-svc:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_PASSWORD=postgres     
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: 
