apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-service
        image: ecomapp-users-service:latest  # Replace with your actual image name
        ports:
        - containerPort: 8000
        env:
        - name: DBHOST
          value: "db-svc"
        - name: DBPORT
          value: "5432"
        - name: DBUSER
          value: "postgres"
        - name: DBPASS
          value: "postgres"
        - name: DBNAME
          value: "postgres"
        - name: ORDERSERVICEPORT
          value: "8001"
        - name: ORDERSERVICEHOST
          value: "orders-deployment"  # Corrected value

